name: Feature | Fix branche
on:
    push:
        branches:
            - 'feature**'
            - 'fix**'
jobs:
    python-ci:
        uses: ./.github/workflows/python-ci.yml
        secrets: inherit
